<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'SuperClosure\\' => array($vendorDir . '/jeremeamia/superclosure/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PhpDocReader\\' => array($vendorDir . '/php-di/phpdoc-reader/src/PhpDocReader'),
    'Invoker\\' => array($vendorDir . '/php-di/invoker/src'),
    'DI\\' => array($vendorDir . '/php-di/php-di/src'),
);
